#Copyright (C) 2018 Fernando Porrino Serrano.
#This software it's under the terms of the GNU Affero General Public License version 3.
#Please, refer to (https://github.com/FherStk/DocumentPlagiarismChecker/blob/master/LICENSE) for further licensing details.

global:
  folder: 'C:\test\M10DAM-LL6'
  sample: 'C:\test\M10DAM-LL6\Enunciat.pdf'
  extension: 'pdf'
  display: 'comparator'
  recursive: true